### ISSUE TITLE
Caribu Error after conda installation

### ISSUE THREAD

**Issue by rbarillot** [openalea-incubator/caribu#37]
I have installed caribu from conda source, but I can't run the model

```
from alinea.caribu.CaribuScene import CaribuScene

scene = Scene('~.bgeom')
c_scene = CaribuScene(scene=scene)
raw, aggregated = c_scene.run()
```

[Output]:
```
>>>  canestra has not finished properly => STOP

---------------------------------------------------------------------------
CaribuRunError                            Traceback (most recent call last)
<ipython-input-22-72a23cb1886a> in <module>()
      5 c_scene = CaribuScene(scene=scene)
      6 Viewer.display(scene)
----> 7 raw, aggregated = c_scene.run()
      8 
      9 # Visualisation

C:\Users\~\AppData\Local\Continuum\anaconda2\envs\lpy\lib\site-packages\alinea.caribu-1.4.4-py2.7-win-amd64.egg\alinea\caribu\CaribuScene.pyc in run(self, direct, infinite, d_sphere, layers, height, screen_size, split_face, simplify)
    539                     out = algos['raycasting'](triangles, materials,
    540                                               lights=lights, domain=None,
--> 541                                               screen_size=screen_size)
    542 
    543             if len(bands) == 1:

C:\Users\~\AppData\Local\Continuum\anaconda2\envs\lpy\lib\site-packages\alinea.caribu-1.4.4-py2.7-win-amd64.egg\alinea\caribu\caribu.pyc in raycasting(triangles, materials, lights, domain, screen_size)
    203                   projection_image_size=screen_size,
    204                   resdir=None, resfile=None)
--> 205     algo.run()
    206     out = algo.nrj['band0']['data']
    207     out['Ei'] = get_incident(out['Eabs'], materials)

C:\Users\~\AppData\Local\Continuum\anaconda2\envs\lpy\lib\site-packages\alinea.caribu-1.4.4-py2.7-win-amd64.egg\alinea\caribu\caribu_shell.pyc in run(self)
    403                 self.mcsail(opt)
    404         for opt in self.opticals:
--> 405             self.canestra(opt)
    406         if self.resfile is not None:
    407             import pickle

C:\Users\~\AppData\Local\Continuum\anaconda2\envs\lpy\lib\site-packages\alinea.caribu-1.4.4-py2.7-win-amd64.egg\alinea\caribu\caribu_shell.pyc in canestra(self, opt)
    537             f.close()
    538             print(">>>  canestra has not finished properly => STOP")
--> 539             raise CaribuRunError(''.join(msg))
    540 
    541         if (d / Path("nr.log")).exists():

CaribuRunError: 
```

**Comment by RomainBarillot** [comment]
Using the latest release of Caribu I still have a similar issue with a very simple scene;
`Traceback (most recent call last):
  File "C:\Users\~\AppData\Local\Continuum\anaconda2\envs\~\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-9e9f328c889e>", line 1, in <module>
    raw, aggregated = c_scene.run(direct=True)
  File "C:\Users\~\AppData\Local\Continuum\anaconda2\envs\~\Lib\site-packages\caribu\src\alinea\caribu\CaribuScene.py", line 600, in run
    sensors=sensors)
  File "C:\Users\~\AppData\Local\Continuum\anaconda2\envs\~\Lib\site-packages\caribu\src\alinea\caribu\caribu.py", line 232, in raycasting
    algo.run()
  File "C:\Users\~\AppData\Local\Continuum\anaconda2\envs\~\Lib\site-packages\caribu\src\alinea\caribu\caribu_shell.py", line 434, in run
    self.canestra(opt)
  File "C:\Users\~\AppData\Local\Continuum\anaconda2\envs\~\Lib\site-packages\caribu\src\alinea\caribu\caribu_shell.py", line 582, in canestra
    raise CaribuRunError(''.join(msg))
CaribuRunError
  canestra has not finished properly => STOP`
