### ISSUE TITLE
BUG - ValueError: The number of caribu outputs doesn't match the number of inputs

### ISSUE THREAD

**Issue by artzet-s** [openalea-incubator/caribu#39]
With the conda package alinea.caribu version 7.0.2 a try to compute light on a canopy of maize.

```
(cartibu) ubuntu@machine28d6a132-3e1d-4fa2-bec5-d962ee609a25:~$ Traceback (most recent call last):
  File "caribu_without_plangl.py", line 241, in <module>
    output_filename="canopy.json")
  File "caribu_without_plangl.py", line 219, in compute_light_interception
    raw, agg = cscene.run(direct=True, simplify=True)
  File "/var/lib/miniconda3/envs/cartibu/lib/python2.7/site-packages/alinea.caribu-1.4.4-py2.7-linux-x86_64.egg/alinea/caribu/CaribuScene.py", line 541, in run
    screen_size=screen_size)
  File "/var/lib/miniconda3/envs/cartibu/lib/python2.7/site-packages/alinea.caribu-1.4.4-py2.7-linux-x86_64.egg/alinea/caribu/caribu.py", line 207, in raycasting
    out['Ei'] = get_incident(out['Eabs'], materials)
  File "/var/lib/miniconda3/envs/cartibu/lib/python2.7/site-packages/alinea.caribu-1.4.4-py2.7-linux-x86_64.egg/alinea/caribu/caribu.py", line 148, in get_incident
    raise ValueError("The number of caribu outputs doesn't match the number of inputs")
ValueError: The number of caribu outputs doesn't match the number of inputs

```

**Comment by pradal** [comment]
@artzet-s : this is mainly due to memory limitation. Can we close this issue?

**Comment by artzet-s** [comment]
@pradal Yes, sorry not a real bug.
